def aliasdef():
    name = input("What is your name? ")
    surname = input("What is your surname? ")
    alias = input("What is your alias? ")
    mailcom = input("What account do you have? (For example: gmail, yahoo)")
    domain = input("What domain do you want? (For example: .gr, .com)")

    print("Here are some examples:")
    print("----------")
    print(name, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(alias, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(name, surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, name, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(name, alias, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(alias, name, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, alias, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(alias, surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(name, surname, alias, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(name, alias, surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, name, alias, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, alias, name, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(alias, name, surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(alias, surname, name, "@", mailcom, ".", domain, sep="")
    print("----------")

    print("Reload program to use again")


def noaliasdef():
    name = input("What is your name? ")
    surname = input("What is your surname? ")
    mailcom = input("What account do you have? ")
    domain = input("What domain do you want? ")

    print("Here are some examples:")
    print("----------")
    print(name, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(name, surname, "@", mailcom, ".", domain, sep="")
    print("----------")
    print(surname, name, "@", mailcom, ".", domain, sep="")
    print("----------")
    print("Reload program to use again")
    print("----------")
print("Mail Generator")
print("----------")
print("Please answer the following questions:")

aliasyn = input("Do you have an alias? If yes, type 1. If no, type 2: ")
print("----------")

if aliasyn == "1":
    aliasdef()
elif aliasyn == "2":
    noaliasdef()
else:
    print("ERROR:")
    print("Type only 1 or 2.")
    print("======================")
    print("|-Reload the program-|")
    print("======================")

#STGHECKER#